---
collections:
  - name: community.general
    version: 4.7.0
  - name: community.sops
    version: 1.2.1
  - name: ansible.posix
    version: 1.3.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.1.1
