---
apiVersion: v1
kind: Pod
metadata:
  name: steel-pod
  namspace: default
spec:
  containers:
    - name: steel-container
      image: ghcr.io/potato-blood/steel:latest
      imagePullSecrets:
        - name: steel
