---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beancount-data-claim
  namespace: default
  labels:
    app: beancount
  annotations:
    volume.beta.kubernetes.io/storage-class: "zfs-nfs"
spec:
  storageClassName: zfs-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
