---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: truenas-graphite-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truenas-graphite-exporter
  template:
    metadata:
      labels:
        app: truenas-graphite-exporter
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9108"
        prometheus.io/scrape: "true"
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - image: prom/graphite-exporter:v0.15.0
          name: truenas-graphite-exporter
          args:
            - --graphite.mapping-config=/tmp/graphite_mapping.yaml
            # - --graphite.mapping-strict-match
            # - --log.level=debug
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
          ports:
            - containerPort: 9109
              name: graphite-tcp
              protocol: TCP
            - containerPort: 9109
              name: graphite-udp
              protocol: UDP
            - containerPort: 9108
              name: prometheus
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            defaultMode: 420
            name: truenas-graphite-exporter
