kind: Secret
ansible_user: ENC[AES256_GCM,data:92/ulTSJ,iv:DegGvAc1gHOntfUrhW4F8r9v5EsXDVJEJCS634N5fyo=,tag:EK+W6VqGtc3yb9vCgxBkJw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:GfEWwdYBqRdFviaw,iv:92jS2DrGePD7+SyWyyHRwWrvgGSZxkGhrPBK87dExe8=,tag:aZYEeolPcFnsaal6qEXdoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age165angy86ctnzjrmf8rsm8r7u8lcvactktcgmq0q8vadldv690f7skvxwk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWc2p3bGZVVFVmSmhZN2Rm
            TXc4MUhrRXRzNnZBWnBBOEMrRDczSldwWFNnCmU1dU5TVmlRSXQ3UE5YT216VEhj
            S250elkzcEkrL0pKOStrTGJUd3dOT0EKLS0tIEtobzJRc2V0eDBtNjk1cUFpZUVS
            MUhuSUJNRXNrZWhWTEhwVTAzcEhMa0kKRmtQltJa4pK1ik1kAo0HaSOtVDnF672j
            xaZ2/VSj2FdJCpQDaUgPsDPbEEuJxRcL/nExzqBvz+moLuyOo7ZOBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-05T16:38:36Z"
    mac: ENC[AES256_GCM,data:LrWVFybme1Ng5xJj2FN8oSRDqz8+XecOfFauDONVW8WND77z63V+foR56KbeEG4g3/YL7JAnQV9k/s7uFL8Z8dEzmRgY4/5zu6ZqQ4A5xJr5N8mmVmlrBD8/GSp20F1TJu5Skw1itZP/EOzLH4RY3QrMBH3qwm8Uz8qVS+BkXt8=,iv:b3DdIAK07DicxbKDgsfBSlT9UznqIu9+bzwBDO4Xi5o=,tag:lU5R1u3aR468vD3m0l22iA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
