kind: Secret
ansible_user: ENC[AES256_GCM,data:t+15LX3p,iv:s/OtbAwlo8cCn+lOx4E6QIb5toqaBnYq6PdOjZG/QTE=,tag:+XokQTKhueQl0MAsshI4cg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5CW7pWOkJI76QFNX,iv:WYT5dqVEeUCLKeFsdCm0n33TA4PeWaGGnAckRM2S4dA=,tag:pdWvA6V2BoMfJiifMn+tdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age165angy86ctnzjrmf8rsm8r7u8lcvactktcgmq0q8vadldv690f7skvxwk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aDFma2VPOUZYejVKU0M0
            MVppNWdFaG01MXFaanBkZ1NxUG9aZStMSjBJCk1NZGpwMVFUcS9xSjdTZ3MyNHdZ
            UU5Wb0xBbjdVRGd5c2dzT1FjbUQ1YmsKLS0tIDVkeXREc05xUm9mY3dxR0U0RXQy
            UWs0cmpVM0pGNlpYRFM2ZlhkZ1JVQmsKPkL669XaRNz/VKKqJe0PHI3Ds2lIO+mr
            bGM/EKpt1aOQztpJnKY0nK1HI7jAXt/KozKeHTOes6DS53pP418d8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-05T16:38:35Z"
    mac: ENC[AES256_GCM,data:HfaSh90niJfHuGXNqG9FPgSIl/+pRWcdN18MW7Asc54ZKHainC/mFuLXlWG0dHGVca2e57eWXJEidy5R3nwGVVNCp8vTMtkl7xvVwD2hlxW/Dog7Q7Hc+HthUbBEEgR9d7RYC1tnkU12GlI+ZFm6lreEMZ0ENYJXTIQQE6YYjPY=,iv:yRjs3DE9WG9D0eQM4j9fgDfc+XTg7RY6ReAfdAmv6sg=,tag:taUHFnz2ezmh+xmOvGmMEQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
