apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "${SECRET_POSTGRES_USER}"
            - name: POSTGRES_PASSWORD
              value: "${SECRET_POSTGRES_PASS}"
            - name: PGDATA
              value: "/data"
          ports:
            - name: db
              containerPort: 5432
          volumeMounts:
            - mountPath: /data
              name: postgres-data-storage
      volumes:
        - name: postgres-data-storage
          persistentVolumeClaim:
            claimName: postgres-data-claim
