# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:6ofUpv+oQCjK,iv:mYagML068KkbKcUQmaoVcTXQEwyNfgtyQkRf/4NR9Y0=,tag:JD8z5pQEtBRab51Dveee9g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:SQEvUwaTLQrONynh9VI1wbd2,iv:VqgjXTZeZMO9OBgVQKhK1b6fyxsGvRqZP886FCDTa5c=,tag:PELuid3w9Z4xD//IX0qH1w==,type:str]
    SECRET_GF_USER: ENC[AES256_GCM,data:pqvm/J8=,iv:Hg5RpLFhkYvRd2Mn72Szk99FbK16R0Nn6So9EqQKW0s=,tag:25Xc6YIqiXxGm3Cco/9jNg==,type:str]
    SECRET_GF_PASS: ENC[AES256_GCM,data:HTpIgSqBgZbylSX/gjIOMeQXGpf1RDmqnw==,iv:YvmziUwIpIpYzCjCI7wCmXTk04leeukoJsFz3rLQzS0=,tag:p6G9v3HoZqCpoz2TLWsIWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age165angy86ctnzjrmf8rsm8r7u8lcvactktcgmq0q8vadldv690f7skvxwk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNjZIUzdJckRBTDN4THk0
            TTZsNnY4T3A2bngvZmZ6SDR4TWR6cVR5ekJnCk81VGVYeTYzZVFvOGd4cS9MSWE5
            QVlSV2hRaU9aTWk0b29XT3VsQ0plTzQKLS0tIExVZ1NqelVzM0Mwalp3bXNLVGQx
            OHI4akx0MDN4S1RSaW1LcHBOem1pQ3MKk/eyyn/26x5g/u7/dO2GjU2AM3FlIKlc
            C+LlY/fbi5R93qJN7H40L+0MbWkRJe+ME/kMVMdnFF7+xLRzkaUMQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-02T20:28:21Z"
    mac: ENC[AES256_GCM,data:ji7/HiaN7sO26iXKh3OU6MX9p3AN9dMcLdUwTfyvfkNAzSO7REdLFlu+mp5/JEhhXu6bKkfxv1JN5lPUA3shgKKi1DFw36g+FIVPZSQn5Vt5Yh8UbyFu/ajCh7A/CHy/kZjz+t1UKYHhYUvMXAK/18plM56/pp8e6q4CU3FlTHI=,iv:E9icWzOIPfFX7VKd27wImryfCYI7ncUPcdO3ZET5hLM=,tag:B0ppc5VoN92XnYQYudcLRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
