# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:w4EzTNfUsZIz,iv:nJ2QE0XYmGK6CnYgyGX9hHlqzzaQa2Eax+SKb6dJyrE=,tag:5PkasShBUIeWk5Cam3A4fg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:yWe+rzD5N0fGtp8mjF8UIjVQ,iv:92bMq48t6nvyNdvY1JtzXhySXTdLuSeIQvoVdT/ciLY=,tag:4J+MV+S2V7XwOIeCKeO9Rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age165angy86ctnzjrmf8rsm8r7u8lcvactktcgmq0q8vadldv690f7skvxwk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcHRVRkRpa2VBWU5Wa1FJ
            UFZCRmdTb1Q0dTZna1ZzK3RDL005NlpVT0RVCkpOUUdFOGlHYjN2TjZwNm95MzZ3
            Ly9md0MrZTBnSHpoektsVzAwZEJ3cVEKLS0tIDE3SEtiYk85TkYzTWpZWExUYXRj
            VjFFcWZHaDhSVzl0cUJxcGwrc2Y2QkkK+5LiNsRuRqOrO0N6j0oyUB/dRzgwLnnB
            1yRQjMlEszVb5yiKqstMVvYedKUZ3My9hJOyYH1tHic/gtX5xYm5XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-05T16:38:35Z"
    mac: ENC[AES256_GCM,data:nOuzbn3d9IQvZ/M2T5488tvvCdm6Sgep3UBTi3wymmDptG02b0rLkWb1wu1wX3VclGDzNVWd+Dj3PZSFuosXC1mE0vDHJQ7/Yo1ljY+Ga58XU+PV9VjCMiTsynyo8cUuuYn10fpJV/tgE8nERJDwFpblWlNKotF9Iu7IhWg37Gc=,iv:4p9ojmh6Pv5in3LzB51+6yeuEoxPMkPn8nhrSg9hDS0=,tag:+QokIQWCHAMx9QAPPEy5OA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
