---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbit-config-claim
  namespace: media
  labels:
    app: qbit
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
