---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-code
  namespace: default
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              # Update this to the latest available and then enable Renovate on
              # the manifest
              image: renovate/renovate:37.224-full
              args:
                - AmrikSD/code
              # Environment Variables
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: GITHUB_COM_TOKEN
                  value: "${SECRET_RENOVATE_PAT}"
                - name: RENOVATE_AUTODISCOVER
                  value: "false"
                - name: RENOVATE_GIT_AUTHOR
                  value: "Renovate Bot <bot@renovateapp.com>"
                - name: RENOVATE_PLATFORM
                  value: "github"
                - name: RENOVATE_TOKEN
                  value: "${SECRET_RENOVATE_PAT}"
          restartPolicy: Never
