---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-pogo
  namespace: default
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              # Update this to the latest available and then enable Renovate on
              # the manifest
              image: renovate/renovate:36.67-full
              args:
                - Potato-Blood/pogo
              # Environment Variables
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: GITHUB_COM_TOKEN
                  value: "${SECRET_RENOVATE_PAT}"
                - name: RENOVATE_AUTODISCOVER
                  value: "false"
                - name: RENOVATE_GIT_AUTHOR
                  value: "Renovate Bot <bot@renovateapp.com>"
                - name: RENOVATE_PLATFORM
                  value: "github"
                - name: RENOVATE_TOKEN
                  value: "${SECRET_RENOVATE_POTATOBLOOD_PAT}"
          restartPolicy: Never
