apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    serviceMonitorSelector: prometheus
  name: promscrape
  namespace: monitoring
spec:
  jobLabel: "test"
  podMetricsEndpoints:
    - interval: 30s
      port: prometheus
      path: /metrics
  namespaceSelector:
    matchNames:
      - networking
      - monitoring
      - default
  selector:
    matchLabels:
      prometheus.io/scrape: "true"
