apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceMonitorSelector: prometheus
  name: promscrape
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      targetPort: 9091
      path: /metrics
  namespaceSelector:
    matchNames:
      - networking
      - monitoring
      - default
  selector:
    matchLabels:
      prometheus.io/scrape: "true"
