
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-claim
  namespace: monitoring
  labels:
    app: prometheus
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
