---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-claim
  namespace: monitoring
  labels:
    app: prometheus
    volume.beta.kubernetes.io/storage-class: "zfs-nfs"
  annotations:
    volume.beta.kubernetes.io/storage-class: "zfs-nfs"
spec:
  storageClassName: zfs-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
