---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-conf
  labels:
    name: alertmanager-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: discord

    receivers:
    - name: discord
      discord_configs:
      - webhook_url: ${SECRET_ALERTMANAGER_DISCORD_WEBHOOK_URL}
