apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceMonitorSelector: prometheus
  name: traefik
  namespace: networking
spec:
  endpoints:
    - interval: 30s
      targetPort: 8082
      path: /metrics
  namespaceSelector:
    matchNames:
      - networking
      - prometheus
  selector:
    matchLabels:
      operated-prometheus: "true"
