---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.3.100.1-10.3.100.100
  METALLB_K8S_GATEWAY_ADDR: 10.3.100.1
  METALLB_TRAEFIK_ADDR: 10.3.100.2
