---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: jackett
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: jackett
  policy:
    semver:
      range: 0.20.x
