---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: truenas-nfs
  namespace: democratic-csi
spec:
  interval: 5m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    driver:
      config:
        driver: freenas-nfs
      existingConfigSecret: dcsi-nfs-secret

    csiDriver:
      name: "org.democratic-csi.nfs"
      version: 1.5.0

    csiProxy:
      image: docker.io/democraticcsi/csi-grpc-proxy:v0.5.3

    controller:
      podAnnotations: {}
      driver:
        image: docker.io/democraticcsi/democratic-csi:latest
        logLevel: info

    node:
      podAnnotations: {}
      podLabels: {}
      priorityClassName: ""
      livenessProbe:
        enabled: true
      cleanup:
        image: docker.io/busybox:1.32.0
      driver:
        image: docker.io/democraticcsi/democratic-csi:latest
        logLevel: info

    storageClasses:
      - name: zfs-nfs
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
        mountOptions:
          - nfsvers=4
          - nconnect=8
          - hard
          - intr
          - noatime
          - nodiratime
        annotations: {}
        labels: {}
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
