apiVersion: v1
kind: Secret
metadata:
  name: nfs-zfs
  namespace: democratic-csi
type: Opaque
data:
  driver-config-file.yaml: |
    driver: freenas-nfs
    httpConnection:
      allowInsecure: true
      host: 10.2.1.2
      password: $SECRET_TRUENAS_PASS
      port: 80
      protocol: http
      username: $SECRET_TRUENAS_USER
    instance_id:
    nfs:
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareCommentTemplate: '{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name]
        }}'
      shareHost: 10.2.1.2
      shareMapallGroup: ""
      shareMapallUser: ""
      shareMaprootGroup: wheel
      shareMaprootUser: root
    sshConnection:
      host: 10.2.1.2
      port: 22
      username: $SECRET_TRUENAS_USER
        #password: "$SECRET_TRUENAS_PASS"
      privateKey: $SECRET_TRUENAS_SSH
    zfs:
      cli:
        sudoEnabled: true
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetParentName: pool_01/k8s/n/v
      datasetPermissionsGroup: 0
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetProperties:
        org.freenas:description: '{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}'
      detachedSnapshotsDatasetParentName: pool_01/k8s/n/s
