# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: truenas-api-key
    namespace: storage-manager
stringData:
    SECRET_TRUENAS_API_KEY: ENC[AES256_GCM,data:rwEkt2jTV+aWhP0d/HfNQU2vp4n8TodVRRFU//8+i+XQLlRW6AgCuPqXmecb9m8nGGUtEkLs8p3sxLCjDubvTBGZ,iv:PieCL+J3ChNaoYyL/IFA3yJTMN31U6rRCliS0UMuz1k=,tag:0XR/d/tU9g9PnkOTE+s5tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age165angy86ctnzjrmf8rsm8r7u8lcvactktcgmq0q8vadldv690f7skvxwk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dEhHcDlTTngzbzNydzhu
            V0JBL1BHZTZQWkpscm9yeTlDbEVKQ0Y1YlVvCnNjUWxkanhUeDBvWlhsTDdzcjZV
            N0czSmdqOElWNFpGczNBMWVKanJBdEEKLS0tIGRHc0dtUGQyQXlYa1JzbDBCNzBH
            YmhwcTlKQlV0V1hzYnlJRHRaTHBFMUkKJdJoLWb3ZFqSSBmytALEfHjRkfuNOnqa
            rj2BVlW7V81v64iE3ch97O8v0PiRkM4QHCkNUcPxRAQ6nrqEv5XjWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-29T21:08:35Z"
    mac: ENC[AES256_GCM,data:HIqHNHj3MZriuix8Q1kUDy4IktpiSoNzY3eLLcdikFS+6nlL8kXVD7B1vXS6MyIcml3EEWySNucyObD5C6GT8RgtAMub2JjGptDl2GIS9u+LminTe4wbldZeHp8uJd+OYEWv7Ka86PKBplnBcmQWXfCikxmL92giJd8s7ZXl5/s=,iv:jM35XRps2Fx6hLOU1eRGuy7erSdoZnlmBKWfNArlnnI=,tag:RxPPQ8KJIJd2ompMi5bIFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
