# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: truenas-api-key
    namespace: kube-system
stringData:
    SECRET_TRUENAS_USER: ENC[AES256_GCM,data:Sgla/g==,iv:ENYjPbvFDjaLHRX9KeJGwCcxrMnA4RCP0/KPgjaTArc=,tag:s1sCtgrnd8x/a0NM3FDbyQ==,type:str]
    SECRET_TRUENAS_PASS: ENC[AES256_GCM,data:cHT+lN9SCAJhhp6O,iv:GeBrtkqNx1cHOdxg00jz/R8Fd7I7U/oCf3mK8Aqtmw8=,tag:6ur4/sVsRlVVwBMXldGgmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age165angy86ctnzjrmf8rsm8r7u8lcvactktcgmq0q8vadldv690f7skvxwk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dEhHcDlTTngzbzNydzhu
            V0JBL1BHZTZQWkpscm9yeTlDbEVKQ0Y1YlVvCnNjUWxkanhUeDBvWlhsTDdzcjZV
            N0czSmdqOElWNFpGczNBMWVKanJBdEEKLS0tIGRHc0dtUGQyQXlYa1JzbDBCNzBH
            YmhwcTlKQlV0V1hzYnlJRHRaTHBFMUkKJdJoLWb3ZFqSSBmytALEfHjRkfuNOnqa
            rj2BVlW7V81v64iE3ch97O8v0PiRkM4QHCkNUcPxRAQ6nrqEv5XjWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-30T01:40:19Z"
    mac: ENC[AES256_GCM,data:LYachoRpQ3Q7vdQM/nfepv5BwmPyxdFIBVdUjX/Z3GUWAOdIEbUGv8S3WUCB/xQdmP8ARjDgAgNhFid6AhLWi3uCJZVNYv8GZJ26l8e29KtcL1dB6wWsdNRkAXtdi3JaPZBGn5cFZC3i0m6HV9554VUK74xw4GQ8Z38siuL2osA=,iv:DItvIMhXpkXj1dqzbBWMG9742AmDVeyiMGQ4rA8D17s=,tag:3oE2IKDlbJVxWLVPGZlphA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
