---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - hajimari-registry.yaml
  - hajimari-policy.yaml
  - flux-system-automation.yaml
  - charts
patchesStrategicMerge:
  - ./gotk-patches.yaml
