name: Mergable

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  label:
    if: contains(github.event.pull_request.labels.*.name, 'DONT MERGE')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is has don't merge label
        run: |
          echo "This PR has a don't merge label"
          exit 1
