---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: hajimari
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hajimari
  policy:
    semver:
      range: x.x.x
